Begin work on Sector deletion

diff --git a/avorion-server/root/usr/local/bin/avorion-cmd b/avorion-server/root/usr/local/bin/avorion-cmd
--- a/avorion-server/root/usr/local/bin/avorion-cmd
+++ b/avorion-server/root/usr/local/bin/avorion-cmd
@@ -2,6 +2,7 @@
 
 CMDVERS='0.5.1'
 CMDNAME="$(basename "$0")"
+EDATE="$(date %s)"
 
 # void say <string, ...>
 #	Ouput the strings passed to stdout and return
@@ -188,7 +189,7 @@ function __set_globals () {
 	readonly _wht="$(tput setaf 7)"
 	readonly _tmuxconf=/etc/avorioncmd-tmux.conf
 	readonly _tmuxcmd="$(which tmux)"
-
+	readonly _regex_sector='(^(-|)[0-9]{1,3}$|^(-|)[0-9]{1,3}:(-|)[0-9]{1,3}-(-|)[0-9]{1,3}:(-|)[0-9]{1,3}$)'
 	declare _tmuxsess _tmuxsock _instdir
 }
 
@@ -258,8 +259,67 @@ function __perform_backup () {
 	true
 }
 
+# bool __perform_sector_reset <options> <int/string, ...>
+#	Delete the sectors passed. The sectors can either be defined
+#	individually or as part of a range using:
+#	
+#	int:int-int:int
+#	
+#	With the first set being the range of x values, and the second
+#	being the range of y values.
+#	Valid options include:
+#		-f	Force no prechecks, just perform the deletion (NO BACKUPS)
+#		-y	Assume yes, still skips prechecks, but saves backups.
 function __perform_sector_reset () {
-	true
+	local _save _sector _bakdir _secdir
+	local -a _sector_array
+	_save=0; 
+	_secdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sectors/${EDATE}"
+
+	if yesno "Would you like to save backups?"; then
+		_save=1
+		_bakdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sector_backup"
+		if [[ ! -d "${_bakdir}" ]]; then
+			mkdir -p "${_bakdir}" \
+				|| die "Unable to create backup directory! Aborting."
+		fi
+	fi
+
+	while (( $# > 0 )); do
+		
+		# If the 1st and 2nd arg (of this run) are just integers, then
+		# do a run of the sector they represent.
+		if [[ "$1" =~ ^(-|)[0-9]$ ]] && [[ "$2" =~ ^(-|)[0-9]$ ]]; then
+			_sector="${1}_${2}"
+			[[ ! -f "${_secdir}/${_sector}" ]] || {
+				say "Sector <${_sector}> doesn't exist. Skipping"
+				shift; shift; continue
+			}
+			
+			_sector_array+=( "${_secdir}/${_sector}" )
+
+			shift; shift; continue
+		fi
+
+		# If the arguments are a range in the format of 
+	done
+
+	(( ${#_sector_array[@]} < 1 )) && {
+		say "No sectors to be processed. Aborting."
+		exit 0
+	}
+	
+	yesno "WARNING: Delete ${#_sector_array[@]} sectors?" || {
+		say "Aborted due to user input"
+		exit 0
+	}
+
+	for _sector in "${_sector_array[@]}"; do
+		(( $_save == 1 )) \
+			&& cp "${_sector}" "$_bakdir"
+		
+		rm "${_sector}"
+	done
 }
 
 # bool __perform_config_edits <string, string>
@@ -439,7 +499,7 @@ function main () {
 			for _secarg in "${@}"; do
 				# Regex to match the following cases: x, y, or x1:y1-x2:y2
 				# while supporting negatives.
-				[[ "$_secarg" =~ (^(-|)[0-9]{1,3}$|^(-|)[0-9]{1,3}:(-|)[0-9]{1,3}-(-|)[0-9]{1,3}:(-|)[0-9]{1,3}$) ]] \
+				[[ "$_secarg" =~ ${_regex_sector}  ]] \
 					|| die "Invalid Sector Parameter: <${_secarg}>"
 			done
 
