Add start/stop/restart and fix regex errors

diff --git a/avorion-server/root/usr/local/bin/avorion-cmd b/avorion-server/root/usr/local/bin/avorion-cmd
--- a/avorion-server/root/usr/local/bin/avorion-cmd
+++ b/avorion-server/root/usr/local/bin/avorion-cmd
@@ -2,7 +2,7 @@
 
 CMDVERS='0.5.1'
 CMDNAME="$(basename "$0")"
-EDATE="$(date %s)"
+EDATE="$(date +%s)"
 
 # void say <string, ...>
 #	Ouput the strings passed to stdout and return
@@ -18,9 +18,9 @@ function say () {
 #	the arguments passed to this function. Otherwise,
 #	return code 1
 function dbgsay () {
-	[[ "${VERBOSE}" == 1 ]] \
-		&& say "$@" \
-		|| return 1
+	[[ "${VERBOSE}" == 1 ]] &&\
+		say "$@" ||\
+		return 1
 }
 
 # int die <options> <string>
@@ -28,7 +28,7 @@ function dbgsay () {
 #	with status code 1 (or the code given with -c)
 function die () {
 	local _code=1
-	if [[ "$1" -eq '-c' ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+	if [[ "$1" -eq '-c' ]] && [[ "$2" =~ ^[0-9][0-9]*$ ]]; then
 		_code="$2"
 		shift; shift
 	fi
@@ -48,7 +48,7 @@ function yesno () {
 
 	while true; do
 		printf '%s' "${_prompt}> "
-		read _answer
+		read -r _answer
 
 		case "${_answer}" in
 			[yY][eE][sS] | [yY])
@@ -69,10 +69,10 @@ function yesno () {
 #	int does not equal 1
 function plural () {
 	if [[ "$1" =~ ^[0-9]+$ ]]; then
-		(( $1 != 1 )) || {
+		if ! (( $1 != 1 )); then
 			printf '%s' 's'
 			return 0
-		}
+		fi
 		return 0
 	fi
 
@@ -91,16 +91,17 @@ function __check_requirements () {
 	_requires[tmux]='-V=^[0-9]?[2-9].[0-9].*'
 	_requires[bash]='--verson=^GNU bash, version [0-9]?[4-9].*'
 	_requires[sed]='--version=^sed (GNU sed) [0-9]?[4-9].*'
+	_requires[steamcmd]='=.*'
 
 	for _prog in "${!_requires[@]}"; do
 		_arg="${_requires["$_prog"]%%=*}"
 		_string="${_requires["$_prog"]##*=}"
 
-		command -v $_prog \
-			|| die "${_prog} is required but not installed!"
+		command -v "$_prog" >/dev/null 2>&1 ||\
+			die "${_prog} is required but is eithernot installed, or not in \$PATH"
 
-		[[ "$("$_prog" "$_arg")" =~ $_string ]] \
-			|| die "${_prog} doesnt meet the minimum version requirements"
+		[[ "$("$_prog" "$_arg")" =~ $_string ]] ||\
+			die "${_prog} doesnt meet the minimum version requirements"
 	done
 }
 
@@ -115,8 +116,8 @@ function __assert_valid_execution () {
 	__check_requirements
 
 	# Die if there are no arguments passed
-	[[ $# -eq 0 ]] \
-		|| die "Usage: avorion-cmd <options> <parameters>"
+	[[ $# -eq 0 ]] ||\
+		die "Usage: avorion-cmd <options> <parameters>"
 
 	# Die if we are running in a screen or tmux session.
 	# TODO: Migrate check to functions that operate on TMUX sessions
@@ -137,9 +138,9 @@ function __assert_valid_execution () {
 #	Check the string given for bash symbols
 #	and return error if any are found.
 function __assert_valid_user_input () {
-	[[ "$1" =~ [/\\$\&@#\`~=+{}\[\]|\'\"] ]] \
-		&& return 1 \
-		|| return 0
+	[[ "$1" =~ [/\\\$\&\@\#\`\~\=\+\{\}\[\]\|\'\"] ]] &&\
+		return 1 ||\
+		return 0
 }
 
 # int __validate_setting_conf <void>
@@ -149,8 +150,8 @@ function __assert_valid_user_input () {
 #	are both valid configs, and that the settings
 #	provided are valid.
 function __validate_setting_conf () {
-	[[ -f /etc/avorionsettings.conf ]] \
-		|| die "Avorion configuration file not found"
+	[[ -f /etc/avorionsettings.conf ]] ||\
+		die "Avorion configuration file not found"
 
 	local -A __conf_vars
 	local __bad_symbols __err
@@ -173,31 +174,31 @@ function __validate_setting_conf () {
 		__err="Configuration error on line ${i} of /etc/avorionsettings.conf"
 		
 		# We dont care about blank lines, so skip those
-		[[ "${__l}" =~ ^[ \t]*$ ]] && continue
+		[[ "${__l}" =~ ^[[:space:]]*$ ]] && continue
 
 		# Ensure the line contains no invalid symbols
-		[[ "${__l}" =~ $__bad_symbols ]] \
-			&& die "${__err} -- Invalid chars present: <${__l}>"
+		[[ "${__l}" =~ $__bad_symbols ]] &&\
+			die "${__err} -- Invalid chars present: <${__l}>"
 		
 		# Ensure that the variable declaration syntax is valid.
 		# We also use this to assign the captured strings to the
 		# BASH_REMATCH environment variable.
-		[[ "${__l}" =~ ^([^ \t]+)=([^ \t]+)$ ]] \
-			|| die "${__err} -- Bad syntax: <${__l}>"
+		[[ "${__l}" =~ ^([^[:space:]][^[:space:]]*)=([^[:space:]][^[:space:]]*)$ ]] ||\
+			die "${__err} -- Bad syntax: <${__l}>"
 
 		# Ensure that the variable being declared is actually
 		# a setting that we will be making use of.
-		[[ -z "${__conf_vars["${BASH_REMATCH[1]}"]}" ]] \
-			&& die "${__err} -- Invalid setting: <${BASH_REMATCH[1]}>"
+		[[ -z "${__conf_vars[${BASH_REMATCH[1]}]}" ]] &&\
+			die "${__err} -- Invalid setting: <${BASH_REMATCH[1]}>"
 
 		# Make sure that the values given to the variable match a
 		# set syntax.
 		#
 		# TODO: Perform some deeper checks here. IE, we would
-		#       want to catch things like having the admin grp
+		#       want to catch things like having the admin group
 		#       set to sudo.
-		[[ "${BASH_REMATCH[2]}" =~ ${__conf_vars[${BASH_REMATCH[1]}]} ]] \
-			|| die "${__err} -- Invalid assignment: <${__l}>"
+		[[ "${BASH_REMATCH[2]}" =~ ${__conf_vars[${BASH_REMATCH[1]}]} ]] ||\
+			die "${__err} -- Invalid assignment: <${__l}>"
 
 	done < /etc/avorionsettings.conf
 	
@@ -247,9 +248,59 @@ function __set_globals () {
 	readonly _wht="$(tput setaf 7)"
 	readonly _tmuxconf=/etc/avorioncmd-tmux.conf
 	readonly _tmuxcmd="$(which tmux)"
-	readonly _regex_sector_arg='^-?[0-9]{1,3}:-?[0-9]{1,3}(--?[0-9]{1,3}:-?[0-9]{1,3}|)$'
-	readonly _regex_sector_num='-?[0-9]{1,3}'
+	readonly _steamcmd="$(which steamcmd)"
+	readonly _regex_sector_arg='^-{0,1}[0-9]{1,3}:-{0,1}[0-9]{1,3}(--{0,1}[0-9]{1,3}:-{0,1}[0-9]{1,3}|)$'
+	readonly _regex_sector_num='-{0,1}[0-9]{1,3}'
 }
+
+function __start_avorion_instance () {
+	printf 'Attempting to starting <%s....n' "${__inst}"
+	if ! systemctl status avorion@"$1" >/dev/null 2<&1; then
+		if sudo -n systemctl start avorion@"$1" >/dev/null 2>&1; then
+			printf "${_grn}%s${_clr}" 'Success'
+			return 0
+		fi
+		
+		printf "${_red}%s${_clr}" 'Fail'
+		return 1
+	fi
+
+	return 0
+}
+
+function __stop_avorion_instance () {
+	local _time=0
+	if ! systemctl status avorion@"$1"; then
+		return 0
+	fi
+
+	printf 'Stopping <%s> instance, this could take a while' "$1"
+	"$_tmuxcmd" -f "${_tmuxconf}" -S "${AVORION_SERVICEDIR}/sockets/${1}.sock" \
+		send-keys ENTER "/say Stopping Avorion..." ENTER "/save" ENTER "/stop"
+
+	while pgrep -a AvorionServer | grep -q "/${1}.sock"; do
+		if ((_time < 1000 )); then
+			printf '.'
+		else
+			printf '\nInstance <%s> seems to be hanging, forcefully shutting down. This make take a moment.' "$1"
+			if ! sudo -n systemctl stop avorion@"$1" >/dev/null 2>&1; then
+				printf '%s' "Unable to stop <$1>. Killing."
+				sudo -n systemctl kill avorion@"$1" >/dev/null 2>&1
+			fi
+		fi
+		((_time++))
+	done
+
+	return 0
+}
+
+function __restart_avorion_instance () {
+	__stop_avorion_instance "$1"
+	__start_avorion_instance "$1" &&\
+		return 0 ||\
+		return 1
+}
+
 
 # void __perform_update <void>
 #	Perform a server update for the Avorion server
@@ -259,62 +310,48 @@ function __set_globals () {
 #	to install avorion if the server was not already
 #	present on the system.
 function __perform_update () {
+	local _units _inst
 
 	# Die if there is already an update running.
-	[[ -d "/tmp/avorion/updatingavorion.lock" ]] \
-		&& die "Update process already running"
+	[[ -d "/tmp/avorion/updatingavorion.lock" ]] &&\
+		die "Update process already running, or a stale lock is present (/tmp/avorion/updatingavorion.lock)."
 
-	mkdir -p /tmp/updatingavorion.lock >/dev/null 2>&1 \
-		|| die "Unable to create avorion lockfile! Check /tmp usage."
+	mkdir -p /tmp/updatingavorion.lock >/dev/null 2>&1 ||\
+		die "Unable to create avorion lockfile! Check /tmp usage."
 
 	# Make sure that the update lock is removed following this
 	# scripts end
 	trap 'rm -rf /tmp/avorion/updatingavorion.lock;echo "Updates unlocked"' EXIT INT TERM
-	local _units _inst
 
 	# Queries the systemd bus for active avorion@ instances and saves them
 	_units="$(systemctl list-units 'avorion@*' | grep -E '^avorion@[^\s]+.service loaded active running' | awk '{print $1}')"
 	
 	# If there were any active instances, stop them.
-	[[ -n "${_units}" ]] && {
-		while read _inst; do
-			_inst="${_inst%%.service}"
-			echo "Stopping <${__inst}>"
-			sudo -n systemctl stop "${__inst}"
+	if [[ -n "${_units}" ]]; then
+		while read -r _inst; do
+			_inst="${_inst%%.service}" #remove trailing .service
+			__stop_avorion_instance "${__inst}"
 		done <<< "${_units}"
-	}
+	fi
 
 	echo "Updates locked."
 
-	# Send the update command (with validation) to the steamcmd instance. We also
-	# have tmux pipe the output of the command to the file $AVORION_SERVICEDIR/steamupdate.log
-	"$_tmuxcmd" -f "${_tmuxconf}" -S "${AVORION_SERVICEDIR}/sockets/steamcmd.sock" \
-		send-keys "force_install_dir \"${AVORION_SERVICEDIR}/${AVORION_BINDIR}\"" ENTER "app_update \"$AVORION_STEAMID\" validate" ENTER \; \
-		pipe-pane "exec cat > ${AVORION_SERVICEDIR}/steamupdate.log" \;
-
-	# As a workaround, since we have the command above operating concurrently,
-	# we follow the new log output until it reaches a stage in which we know
-	# that the Steam updater has completed. Then, we exit using the `q` sed command.
-	tail -n 100 -f "${AVORION_SERVICEDIR}/steamupdate.log" 2>&1 | sed -r '/^(Success!|Failure)/ q'
-	echo 'Done'
-	
-	# Stop outputting to a logfile
-	"$_tmuxcmd" -f "${_tmuxconf}" -S "${AVORION_SERVICEDIR}/sockets/steamcmd.sock" pipe-pane \;
+	# Perform the update
+	"$_steamcmd" +login anonymous +force_install_dir "${AVORION_SERVICEDIR}/${AVORION_BINDIR}" +app_update "$AVORION_STEAMID" validate +exit
 
 	# If any instances were up prior to the update, re-start them
-	[[ -n "${_units}" ]] && {
-		while read _inst; do
+	if [[ -n "${_units}" ]]; then
+		while read -r _inst; do
 			__inst="${_inst%%.service}"
-			echo "Starting <${__inst}>"
-			sudo -n systemctl start "${_inst}"
+			__start_avorion_instance "${_inst}"
 		done <<< "${_units}"
-	}
+	fi
 
 	exit 0
 }
 
 function __perform_backup () {
-	true
+	return 1
 }
 
 # bool __perform_sector_reset <options> <int/string, ...>
@@ -341,8 +378,8 @@ function __perform_sector_reset () {
 		_save=1
 		_bakdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sector_backup"
 		if [[ ! -d "${_bakdir}" ]]; then
-			mkdir -p "${_bakdir}" \
-				|| die "Unable to create backup directory! Aborting."
+			mkdir -p "${_bakdir}" ||\
+				die "Unable to create backup directory! Aborting."
 		fi
 	fi
 
@@ -352,12 +389,12 @@ function __perform_sector_reset () {
 		# Only follow this path if the given argument is a single
 		# coord. Shift and continue execution in the next loop 
 		# after the sector is queued
-		if [[ "$1" =~ ^-?[0-9]{1,3}:-?[0-9]{1,3}$ ]]; then
+		if [[ "$1" =~ ^-{0,1}[0-9]{1,3}:-{0,1}[0-9]{1,3}$ ]]; then
 			_sector="${1//:/_}"
-			[[ -f "${_secdir}/${_sector}" ]] || {
+			if ! [[ -f "${_secdir}/${_sector}" ]]; then
 				dbgsay "Sector <${_sector}> doesn't exist. Skipping."
 				shift; continue
-			}
+			fi
 			dbgsay "Queueing sector: <${_sector}>"
 			_sector_array+=( "${_secdir}/${_sector}" )
 			shift; continue
@@ -367,15 +404,15 @@ function __perform_sector_reset () {
 		# a `_`, here we make use of Bash's ability to store regex capture
 		# an array (BASH_REMATCH) to generate two for loops to queue the
 		# passed sectors.
-		elif [[ "$1" =~ ^(-?[0-9]{1,3}):(-?[0-9]{1,3})-(-?[0-9]{1,3}):(-?[0-9]{1,3})$ ]]; then
+		elif [[ "$1" =~ ^(-{0,1}[0-9]{1,3}):(-{0,1}[0-9]{1,3})-(-{0,1}[0-9]{1,3}):(-{0,1}[0-9]{1,3})$ ]]; then
 			_x1="${BASH_REMATCH[1]}"; _x2="${BASH_REMATCH[2]}"
 			_y1="${BASH_REMATCH[3]}"; _y2="${BASH_REMATCH[4]}"
 			for _x in {"$_x1".."$_x2"}; do
 				for _y in {"$_y1".."$_y2"}; do
-					[[ -f "${_secdir}/${_x}_${_y}" ]] || {
+					if ! [[ -f "${_secdir}/${_x}_${_y}" ]]; then
 						dbgsay "Sector <${_x}_${_y}> doesn't exist. Skipping."
 						continue
-					}
+					fi
 
 					dbgsay "Queuing sector: <${_x}_${_y}>"
 					_sector_array+=( "${_secdir}/${_sector}" )
@@ -390,25 +427,24 @@ function __perform_sector_reset () {
 
 	# Obviously we dont need to continue if there are no
 	# sectors to process
-	(( ${#_sector_array[@]} < 1 )) && {
-		say "No sectors to be processed. Aborting."
+	if (( ${#_sector_array[@]} < 1 )); then
+		say "No sectors to be processed."
 		exit 0
-	}
+	fi
 	
 	# Confirmation of sector deletion. the `plural` function
 	# does exactly what it looks like it does. If the number
 	# is NOT one, return an `s`
-	yesno "WARNING: Delete ${#_sector_array[@]} sector$(plural ${#_sector_array[@]})?" || {
+	if ! yesno "WARNING: Delete ${#_sector_array[@]} sector$(plural ${#_sector_array[@]})?"; then
 		say "Aborted due to user input"
 		exit 0
-	}
+	fi
 
 	# For every sector queued, backup if specified, and then
 	# delete.
 	for _sector in "${_sector_array[@]}"; do
-		(( $_save == 1 )) \
-			&& cp "${_sector}" "$_bakdir"
-		
+		(( _save == 1 )) &&\
+			cp "${_sector}" "$_bakdir"
 		rm "${_sector}"
 	done
 }
@@ -429,14 +465,14 @@ function __perform_config_edits () {
 	local __temp_file="/tmp/avorion-cmd/${__instance}/${__file}.tmp"
 	local __editor
 
-	[[ -w "${__inst_file}" ]] || {
+	if ! [[ -w "${__inst_file}" ]]; then
 		say "Unable to edit file: <${__inst_file}>"
 
 		[[ -f "${__inst_file}" ]] \
 			|| die "File does not exist."
 	
 		die "File is not writable. Are the permissions correct?"	
-	}
+	fi
 
 	if [[ -d "/tmp/avorion-cmd/${__instance}" ]]; then 
 		[[ -f "${__temp_file}" ]] \
@@ -500,7 +536,7 @@ function __show_service_instances () {
 		elif [[ "$_instance" =~ ^steam(cmd|cli)$ ]]; then
 			systemctl status "${_instance}" >/dev/null 2>&1 \
 				&& echo "${_instance} (steamcmd.service) -- ${_grn}Online${_clr}" \
-				|| echo "${_instance} (steamcmd.service) -- ${_red}Offline${_clr}"
+				|| echo "${_instance} (steamcmd.service) -- ${_yel}Offline (normal)${_clr}"
 
 		else
 			if [[ -f "/etc/systemd/system/${_instance}.service" ]]; then
@@ -521,36 +557,54 @@ function main () {
 
 	for _arg do
 		shift
-		[[ "${_arg}" == --debug ]] && {
+		if [[ "${_arg}" == --debug ]]; then
 			VERBOSE=1
 			continue
-		}
+		fi
 		set -- "$@" "${_arg}"
 	done
 
 	case "$1" in
-		attach)
-			__set_tmux_instance "$2" \
-				|| die "${__err_bad_inst} <$2>"
+		start)
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
 
-			"$_tmuxcmd" -f "${_tmuxconf}" -S "$_tmuxsock" attach \
-				|| exit 1 \
-				&& exit 0
+			__start_avorion_instance "$_tmuxsess" ||\
+				exit 1 &&\
+				exit 0
+			;;
+
+		stop)
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
+
+			__stop_avorion_instance "$_tmuxsess" ||\
+				exit 1 &&\
+				exit 0
+			;;
+
+		restart)
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
+
+			__restart_avorion_instance "$_tmuxsess" ||\
+				exit 1 &&\
+				exit 0
 			;;
 		
 		lock)
-			__set_tmux_instance "$2" \
-				|| die "${__err_bad_inst} <$2>"
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
 			exit 0
 			;;
 
-		view)
+		view | attach)
 			__set_tmux_instance "$2" \
 				|| die "${__err_bad_inst} <$2>"
 
-			"$_tmuxcmd" -f "${_tmuxconf}" -S "$_tmuxsock" attach -r \
-				|| exit 1 \
-				&& exit 0
+			"$_tmuxcmd" -f "${_tmuxconf}" -S "$_tmuxsock" attach -r ||\
+				exit 1 &&\
+				exit 0
 			;;
 		
 		exec)
@@ -558,60 +612,60 @@ function main () {
 				|| die "${__err_bad_inst} <$2>"
 
 			shift; shift
-			"$_tmuxcmd" -f "${_tmuxconf}" -S "$_tmuxsock" send-keys "$@" ENTER \; attach -r \
-				|| exit 1 \
-				&& exit 0
+			"$_tmuxcmd" -f "${_tmuxconf}" -S "$_tmuxsock" send-keys "$@" ENTER \; attach -r ||\
+				exit 1 &&\
+				exit 0
 			;;
 		
 		update)
-			__perform_update \
-				|| exit 1 \
-				&& exit 0
+			__perform_update ||\
+				exit 1 &&\
+				exit 0
 			;;
 		
 		showinstances|-I)
-			__show_service_instances \
-				|| exit 1 \
-				&& exit 0
+			__show_service_instances ||\
+				exit 1 &&\
+				exit 0
 			;;
 
 		backup)
-			__get_instance_dir \
-				|| die "${__err_bad_inst} <$2>"
+			__get_instance_dir ||\
+				die "${__err_bad_inst} <$2>"
 
-			__perform_backup "$_instdir" \
-				|| exit 1 \
-				&& exit 0
+			__perform_backup "$_instdir" ||\
+				exit 1 &&\
+				exit 0
 			;;
 
 		config)
-			__set_tmux_instance "$2" \
-				|| die "${__err_bad_inst} <$2>"
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
 
-			[[ "$_tmuxsess" =~ ^[sS][tT][eE][aA][mM] ]] \
-				|| die "Steam configs are not managed by ${CMDNAME}"
+			[[ "$_tmuxsess" =~ ^[sS][tT][eE][aA][mM] ]] ||\
+				die "Steam configs are not managed by ${CMDNAME}"
 
-			__perform_config_edits "$_tmuxsess" "$3" \
-				|| exit 1 \
-				&& exit 0
+			__perform_config_edits "$_tmuxsess" "$3" ||\
+				exit 1 &&\
+				exit 0
 			;;
 
 		resetsector)
-			__set_tmux_instance "$2" \
-				|| die "${__err_bad_inst} <$2>"
+			__set_tmux_instance "$2" ||\
+				die "${__err_bad_inst} <$2>"
 
 			shift; shift
 			
-			for _secarg in "${@}"; do
-				# Regex to match the following cases: x, y, or x1:y1-x2:y2
+			for _secarg in "$@"; do
+				# Regex to match the following cases: x:y, or x1:y1-x2:y2
 				# while supporting negatives.
-				[[ "$_secarg" =~ ${_regex_sector_arg} ]] \
-					|| die "Invalid Sector Parameter: <${_secarg}>"
+				[[ "$_secarg" =~ ${_regex_sector_arg} ]] ||\
+					die "Invalid Sector Parameter: <${_secarg}>"
 			done
 
-			__perform_sector_reset "$@"\
-				|| exit 1 \
-				&& exit 0
+			__perform_sector_reset "$@" ||\
+				exit 1 &&\
+				exit 0
 			;;
 
 		usage|--usage|-u)
@@ -675,7 +729,6 @@ Commands:
 		Reset the given sectors or range of sectors.
 		${_grn}${CMDNAME} resetsectors <instance> <x:y, ...>${_clr}
 		${_grn}${CMDNAME} resetsectors <instance> <x:x-y:y>
-		${_yel}NOTICE: Not currently implemented${_clr}
 	
 	backup
 		Take a backup of the given instance.
