Add verbose output option, and fix some sector regex

diff --git a/avorion-server/root/usr/local/bin/avorion-cmd b/avorion-server/root/usr/local/bin/avorion-cmd
--- a/avorion-server/root/usr/local/bin/avorion-cmd
+++ b/avorion-server/root/usr/local/bin/avorion-cmd
@@ -13,6 +13,12 @@ function say () {
 	return 0
 }
 
+function dbgsay () {
+	[[ "${VERBOSE}" == 1 ]] \
+		&& say "$@" \
+		|| return 1
+}
+
 # int die <options> <string>
 #	Output the strings passed to stdout then exit
 #	with status code 1 (or the code given w
@@ -171,6 +177,7 @@ function __set_tmux_instance () {
 	# file, then use that and set the tmux session
 	elif systemctl status avorion@"$_tmuxsess" >/dev/null 2>&1 || systemctl status "${_tmuxsess}" >/dev/null 2>&1; then
 		_tmuxsock="${AVORION_SERVICEDIR}/sockets/${_tmuxsess}.sock"
+
 	else
 		echo "$_tmuxsess is not a valid instance"
 		exit 1
@@ -181,6 +188,9 @@ function __set_tmux_instance () {
 #	Set various global values, and declare
 #	other unset globals
 function __set_globals () {
+	declare VERBOSE=0
+	declare _tmuxsess _tmuxsock _instdir
+	
 	readonly _clr="$(tput sgr0)"
 	readonly _bld="$(tput bold)"
 	readonly _red="$(tput setaf 1)"
@@ -189,8 +199,8 @@ function __set_globals () {
 	readonly _wht="$(tput setaf 7)"
 	readonly _tmuxconf=/etc/avorioncmd-tmux.conf
 	readonly _tmuxcmd="$(which tmux)"
-	readonly _regex_sector='(^(-|)[0-9]{1,3}$|^(-|)[0-9]{1,3}:(-|)[0-9]{1,3}-(-|)[0-9]{1,3}:(-|)[0-9]{1,3}$)'
-	declare _tmuxsess _tmuxsock _instdir
+	readonly _regex_sector_arg='(^((-|)[0-9]{1,3})$|^((-|)[0-9]{1,3}):((-|)[0-9]{1,3})-((-|)[0-9]{1,3}):((-|)[0-9]{1,3})$)'
+	readonly _regex_sector_num='(-|)[0-9]{1,3}'
 }
 
 # void __perform_update <void>
@@ -240,7 +250,7 @@ function __perform_update () {
 	tail -n 100 -f "${AVORION_SERVICEDIR}/steamupdate.log" 2>&1 | sed -r '/^(Success!|Failure)/ q'
 	echo 'Done'
 	
-	# Stop outputing to a logfile
+	# Stop outputting to a logfile
 	"$_tmuxcmd" -f "${_tmuxconf}" -S "${AVORION_SERVICEDIR}/sockets/steamcmd.sock" pipe-pane \;
 
 	# If any instances were up prior to the update, re-start them
@@ -272,6 +282,7 @@ function __perform_backup () {
 #		-y	Assume yes, still skips prechecks, but saves backups.
 function __perform_sector_reset () {
 	local _save _sector _bakdir _secdir
+	local _x1 _x2 _y1 _y2
 	local -a _sector_array
 	_save=0; 
 	_secdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sectors/${EDATE}"
@@ -286,22 +297,31 @@ function __perform_sector_reset () {
 	fi
 
 	while (( $# > 0 )); do
-		
-		# If the 1st and 2nd arg (of this run) are just integers, then
-		# do a run of the sector they represent.
-		if [[ "$1" =~ ^(-|)[0-9]$ ]] && [[ "$2" =~ ^(-|)[0-9]$ ]]; then
-			_sector="${1}_${2}"
+		if [[ "$1" =~ ^-?[0-9]{1,3}(:|_|;|.)-?[0-9]{1,3}$ ]]; then
+			_sector="${1//[:\;\.]/_}"
 			[[ ! -f "${_secdir}/${_sector}" ]] || {
 				say "Sector <${_sector}> doesn't exist. Skipping"
 				shift; shift; continue
 			}
-			
+			dbgsay "Queueing sector: <${_sector}>"
 			_sector_array+=( "${_secdir}/${_sector}" )
 
 			shift; shift; continue
 		fi
 
-		# If the arguments are a range in the format of 
+		if [[ "$1" =~ ^(-?[0-9]{1,3}):(-?[0-9]{1,3})-(-?[0-9]{1,3}):(-?[0-9]{1,3})$ ]]; then
+			_x1="${BASH_REMATCH[1]}"; _x2="${BASH_REMATCH[2]}"
+			_y1="${BASH_REMATCH[3]}"; _y2="${BASH_REMATCH[4]}"
+
+			for _x in {"$_x1".."$_x2"}; do
+				for _y in {"$_y1".."$_y2"}; do
+					dbgsay "Queuing sector: <${_x}_${_y}>"
+					_sector_array+=( "${_secdir}/${_sector}" )
+				done
+			done
+		fi
+
+		die "Bad sector formatting: <${1}>. Aborting."
 	done
 
 	(( ${#_sector_array[@]} < 1 )) && {
@@ -428,6 +448,15 @@ function main () {
 
 	local __err_bad_inst='Invalid instance passed:'
 
+	for _arg do
+		shift
+		[[ "${_arg}" == --debug ]] && {
+			VERBOSE=1
+			continue
+		}
+		set -- "$@" "${_arg}"
+	done
+
 	case "$1" in
 		-a|a|attach)
 			__set_tmux_instance "$2" \
@@ -499,7 +528,7 @@ function main () {
 			for _secarg in "${@}"; do
 				# Regex to match the following cases: x, y, or x1:y1-x2:y2
 				# while supporting negatives.
-				[[ "$_secarg" =~ ${_regex_sector}  ]] \
+				[[ "$_secarg" =~ ${_regex_sector_arg}  ]] \
 					|| die "Invalid Sector Parameter: <${_secarg}>"
 			done
 
@@ -559,7 +588,7 @@ Commands:
 	resetsectors
 		Reset the given sectors or range of sectors.
 		${_grn}${CMDNAME} resetsectors <instance> <x:y, ...>${_clr}
-		${_grn}${CMDNAME} resetsectors <instance> <x:y-x:y>
+		${_grn}${CMDNAME} resetsectors <instance> <x:x-y:y>
 		${_yel}NOTICE: Not currently implemented${_clr}
 	
 	backup
