Test source file for avorion-cmd before loading

diff --git a/avorion-server/root/usr/local/bin/avorion-cmd b/avorion-server/root/usr/local/bin/avorion-cmd
--- a/avorion-server/root/usr/local/bin/avorion-cmd
+++ b/avorion-server/root/usr/local/bin/avorion-cmd
@@ -41,14 +41,39 @@ fi
 
 #####
 
-function __verify_settings_conf () {
-	local -a __conf_vars=( AVORION_ADMIN_GRP AVORION_SERVICEDIR AVORION_BINDIR AVORION_STEAMID )
-	local -a __conf_regx=( '[a-z]{4,}' '[a-zA-Z0-9_\-]{1,}' '[a-zA-Z0-9_\-]{1,}' '[0-9]{2,}' )
-	local __use_defaults
+function __validate_settings_conf () {
+	local -A __conf_vars
+	__conf_vars[AVORION_ADMIN_GRP]='[a-z]{4,}'
+	__conf_vars[AVORION_SERVICEDIR]='[a-zA-Z0-9_\-]{1,}'
+	__conf_vars[AVORION_BINDIR]='[a-zA-Z0-9_\-]{1,}'
+	__conf_vars[AVORION_STEAMID]='[0-9]{2,}'
 
-	grep -cvE "^($(printf '%s' "${__conf_vars[*]}" | tr ' ' '|')|)" >/dev/null || {
-		__use_defaults=1
-	}
+	grep -qcvE "^(($(printf '%s' "${!__conf_vars[*]}" | tr ' ' '|'))=.*|\\s*)" >/dev/null \
+		|| return 1
+
+	local i=0
+	while read -r __l; do
+		local __err="Configuration error on line ${i} of /etc/avorionsettings.conf"
+		
+		# Set line count
+		((i++))
+		
+		# We dont case about blank lines, so skip those
+		[[ "$__l" =~ ^\s*$ ]] \
+			&& continue
+		
+		[[ "$__l" =~ ^([\s]+)=([\s]+)$ ]] \
+			|| die "${__err} -- Bad syntax: <${__l}>"
+
+		[[ -z "${__conf_vars["${BASH_REMATCH[1]}"]}" ]] \
+			&& die "${__err} -- Invalid setting: <${BASH_REMATCH[1]}>"
+
+		[[ "${BASH_REMATCH[2]}" =~ ${__conf_vars[${BASH_REMATCH[1]}]} ]] \
+			|| die "${__err} -- Invalid option passed: <$__l>"
+
+	done < /etc/avorionsettings.conf
+	
+	return 0
 }
 
 source /etc/avorionsettings.conf
