Add version checking as well as many comments

diff --git a/avorion-server/root/usr/local/bin/avorion-cmd b/avorion-server/root/usr/local/bin/avorion-cmd
--- a/avorion-server/root/usr/local/bin/avorion-cmd
+++ b/avorion-server/root/usr/local/bin/avorion-cmd
@@ -54,6 +54,46 @@ function yesno () {
 	done
 }
 
+# int plural <int>
+#	Given an int, print an s to the caller if said
+#	int does not equal 1
+function plural () {
+	if [[ "$1" =~ ^[0-9]+$ ]]; then
+		(( $1 != 1 )) || {
+			printf '%s' 's'
+			return 0
+		}
+		return 0
+	fi
+
+	die "Function \`plural\` recieved <$1> rather than an int"
+}
+# bool __check_requirements <void>
+#	Checks required software versions and exits if either
+#	the required software is not present in $PATH or if it
+#	does not meet the minimum version requirements.
+function __check_requirements () {
+	local -A _requires
+	local _prog _arg _string
+
+	# Required version strings, prepended with the argument
+	# that will invoke them.
+	_requires[tmux]='-V=^[0-9]?[2-9].[0-9].*'
+	_requires[bash]='--verson=^GNU bash, version [0-9]?[4-9].*'
+	_requires[sed]='--version=^sed (GNU sed) [0-9]?[4-9].*'
+
+	for _prog in "${!_requires[@]}"; do
+		_arg="${_requires["$_prog"]%%=*}"
+		_string="${_requires["$_prog"]##*=}"
+
+		command -v $_prog \
+			|| die "${_prog} is required but not installed!"
+
+		[[ "$("$_prog" "$_arg")" =~ $_string ]] \
+			|| die "${_prog} doesnt meet the minimum version requirements"
+	done
+}
+
 # int __validate_process_exec <ARGV>
 #	Run various pre-checks prior to running the main
 #	script body to ensure that the process execution
@@ -62,13 +102,11 @@ function yesno () {
 #	fail, exit the script with error code 1 and give
 #	an explanation.
 function __assert_valid_execution () {
+	__check_requirements
+
 	# Die if there are no arguments passed
 	[[ $# -eq 0 ]] \
 		|| die "Usage: avorion-cmd <options> <parameters>"
-
-	# Die if tmux is not installed
-	command -v tmux >/dev/null 2>&1 \
-		|| die "avorion-cmd requires tmux to function! Please run apt install -y tmux"
 
 	# Die if we are running in a screen or tmux session.
 	# TODO: Migrate check to functions that operate on TMUX sessions
@@ -199,8 +237,8 @@ function __set_globals () {
 	readonly _wht="$(tput setaf 7)"
 	readonly _tmuxconf=/etc/avorioncmd-tmux.conf
 	readonly _tmuxcmd="$(which tmux)"
-	readonly _regex_sector_arg='(^((-|)[0-9]{1,3})$|^((-|)[0-9]{1,3}):((-|)[0-9]{1,3})-((-|)[0-9]{1,3}):((-|)[0-9]{1,3})$)'
-	readonly _regex_sector_num='(-|)[0-9]{1,3}'
+	readonly _regex_sector_arg='^-?[0-9]{1,3}:-?[0-9]{1,3}(--?[0-9]{1,3}:-?[0-9]{1,3}|)$'
+	readonly _regex_sector_num='-?[0-9]{1,3}'
 }
 
 # void __perform_update <void>
@@ -278,8 +316,7 @@ function __perform_backup () {
 #	With the first set being the range of x values, and the second
 #	being the range of y values.
 #	Valid options include:
-#		-f	Force no prechecks, just perform the deletion (NO BACKUPS)
-#		-y	Assume yes, still skips prechecks, but saves backups.
+#		--backup	Force take backups
 function __perform_sector_reset () {
 	local _save _sector _bakdir _secdir
 	local _x1 _x2 _y1 _y2
@@ -287,7 +324,10 @@ function __perform_sector_reset () {
 	_save=0; 
 	_secdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sectors/${EDATE}"
 
-	if yesno "Would you like to save backups?"; then
+	# If the first argument is `--backups` then we don't need to confirm backups, we assume yes.
+	# We also use that opportunity to shift the positional arguments to the left. Since `shift`
+	# will return true, and only runs if the correct argument is found, this is still valid.
+	if { [[ "$1" -eq '--backup' ]] && shift; } || yesno "Would you like to save backups?"; then
 		_save=1
 		_bakdir="${AVORION_SERVICEDIR}/${_tmuxsess}/sector_backup"
 		if [[ ! -d "${_bakdir}" ]]; then
@@ -296,44 +336,60 @@ function __perform_sector_reset () {
 		fi
 	fi
 
+	# While there are still arguments to process
 	while (( $# > 0 )); do
-		if [[ "$1" =~ ^-?[0-9]{1,3}(:|_|;|.)-?[0-9]{1,3}$ ]]; then
-			_sector="${1//[:\;\.]/_}"
+
+		# Only follow this path if the given argument is a single
+		# coord. Shift and continue execution in the next loop 
+		# after the sector is queued
+		if [[ "$1" =~ ^-?[0-9]{1,3}:-?[0-9]{1,3}$ ]]; then
+			_sector="${1//:/_}"
 			[[ ! -f "${_secdir}/${_sector}" ]] || {
 				say "Sector <${_sector}> doesn't exist. Skipping"
-				shift; shift; continue
+				shift; continue
 			}
 			dbgsay "Queueing sector: <${_sector}>"
 			_sector_array+=( "${_secdir}/${_sector}" )
+			shift; continue
 
-			shift; shift; continue
-		fi
-
-		if [[ "$1" =~ ^(-?[0-9]{1,3}):(-?[0-9]{1,3})-(-?[0-9]{1,3}):(-?[0-9]{1,3})$ ]]; then
+		# Only follow this path if the argument given is the defined range
+		# of coordinates. Unlike before where we simply replace the `:` with
+		# a `_`, here we make use of Bash's ability to store regex capture
+		# an array (BASH_REMATCH) to generate two for loops to queue the
+		# passed sectors.
+		elif [[ "$1" =~ ^(-?[0-9]{1,3}):(-?[0-9]{1,3})-(-?[0-9]{1,3}):(-?[0-9]{1,3})$ ]]; then
 			_x1="${BASH_REMATCH[1]}"; _x2="${BASH_REMATCH[2]}"
 			_y1="${BASH_REMATCH[3]}"; _y2="${BASH_REMATCH[4]}"
-
 			for _x in {"$_x1".."$_x2"}; do
 				for _y in {"$_y1".."$_y2"}; do
 					dbgsay "Queuing sector: <${_x}_${_y}>"
 					_sector_array+=( "${_secdir}/${_sector}" )
 				done
 			done
-		fi
 
-		die "Bad sector formatting: <${1}>. Aborting."
+		# Die if the "sector" given is just invalid.
+		else
+			die "Bad sector formatting: <${1}>. Aborting."
+		fi
 	done
 
+	# Obviously we dont need to continue if there are no
+	# sectors to process
 	(( ${#_sector_array[@]} < 1 )) && {
 		say "No sectors to be processed. Aborting."
 		exit 0
 	}
 	
-	yesno "WARNING: Delete ${#_sector_array[@]} sectors?" || {
+	# Confirmation of sector deletion. the `plural` function
+	# does exactly what it looks like it does. If the number
+	# is NOT one, return an `s`
+	yesno "WARNING: Delete ${#_sector_array[@]} sector$(plural ${#_sector_array[@]})?" || {
 		say "Aborted due to user input"
 		exit 0
 	}
 
+	# For every sector queued, backup if specified, and then
+	# delete.
 	for _sector in "${_sector_array[@]}"; do
 		(( $_save == 1 )) \
 			&& cp "${_sector}" "$_bakdir"
@@ -528,7 +584,7 @@ function main () {
 			for _secarg in "${@}"; do
 				# Regex to match the following cases: x, y, or x1:y1-x2:y2
 				# while supporting negatives.
-				[[ "$_secarg" =~ ${_regex_sector_arg}  ]] \
+				[[ "$_secarg" =~ ${_regex_sector_arg} ]] \
 					|| die "Invalid Sector Parameter: <${_secarg}>"
 			done
 
@@ -543,13 +599,13 @@ Avorion Manager v${CMDVERS}
 Usage: ${CMDNAME} <command> <optons> <parameters>
 
 Commands:
-	showinstances
+	showinstances --instances -I
 		Display a listing of all Avorion/Steam instances
-	
-	help
+
+	help --help -h
 		This help text
 	
-	usage
+	usage --usage -u
 		Print the usage text
 	
 	start
